name: Release Obsidian theme

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            manifest.json
            theme.css
          draft: true
